apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/ecommerce-microservices-488103/image-registry/auth-ms
        name: auth-ms
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: jwt_secret
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: database_url
        resources: {}
status: {}
